---
- name: Set up machine
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Create user andmu
      ansible.builtin.user:
        name: andmu
        group: admin
        password: "{{  pass | password_hash('sha512') }}"
        shell: "/bin/bash"

    - name: PasswordAuthentication yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication no"
        state: present
        line: "PasswordAuthentication yes"
        backup: yes

    - name: Restart sshd service
      service:
        name: sshd
        state: restarted

    - name: Install Docker Prerequisites
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker and its dependecies
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a

    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet 
          - kubeadm 
          - kubectl

    - name: Remove /etc/containerd/config.toml
      file:
        path: /etc/containerd/config.toml
        state: absent

    - name: Restart sshd service
      service:
        name: containerd
        state: restarted

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init 

    - name: Setup kubeconfig for andmu user
      command: "{{ item }}"
      with_items:
      - mkdir -p /home/andmu/.kube
      - cp -i /etc/kubernetes/admin.conf /home/andmu/.kube/config
      - chown andmu:admin /home/andmu/.kube/config