Vagrant.configure(2) do |config|
  config.vm.define 'kubernetes-master' do |vm|
    vm.vm.box = 'ubuntu/focal64'
    vm.vm.network 'public_network', ip: '192.168.68.30', bridge: 'Realtek Gaming GbE Family Controller'
    vm.vm.hostname = 'kubernetes-master'
    vm.vm.provider 'virtualbox' do |v|
      v.name = 'kubernetes-master'
      v.memory = 4096
      v.cpus = 2
    end
  end
  config.vm.provision 'ansible_local' do |ansible|
    ansible.playbook = '../Ansible/setup.yaml'
    ansible.extra_vars = {
      pass: 'root'
    }
  end
end
